### ISSUE TITLE
Wont run on Fedora 25 x86_64

### ISSUE THREAD

**Issue by Jmainguy** [Daivuk/lgj17#1]
Guessing by the instructions this was compiled for ARM, can this be compiled for x86_64 as well, is this something I can do with the source?

**Comment by Daivuk** [comment]
No for this I will need to do a port of my engine. The renderer and the audio engine and inputs are kind of specific to the Pi. I'll start a xubuntu port soon so that should cover everything.

**Comment by Daivuk** [comment]
Closing this issue as this is an engine issue, this is the game GitHub and it's only js files :)

**Comment by Daivuk** [comment]
Actually I'll leave it open here also since I'll have to update the binairies

**Comment by Jmainguy** [comment]
Doing some fall cleaning, gonna close this out. Love your work Daivuk.
